name: Check SDK
on:
  workflow_dispatch:
jobs:
  check-sdk:
    runs-on: ubuntu-latest  # 或 macos-latest
    steps:
      - name: Check Java version
        run: echo "$(java --version)"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check Gradle Java version
        run: |
          chmod +x gradlew
          ./gradlew -version

      - name: Check Android SDK
        run: |
          echo "Checking if Android SDK is installed..."
          sdkmanager --version || echo "Android SDK is not installed."
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "PATH: $PATH"

      - name: Check Gradle Java version
        run: gradlew -version
